##################################################################
#                          FarmAssist                            #
##################################################################
use-permissions: true
##################################################################
#                        Global Settings                         #
##################################################################
# Anything set under global settings will be globally set,
# Even if you give the permission these settings will override it.
# Example:
# player has farmassist.wheat
# wheat:
#   Enabled: false
# player won't be able to auto-replant wheat.
wheat:
    enabled: true
    replant-when-ripe: false
    plant-on-till: true
sugar_cane:
    enabled: true
nether_wart:
    enabled: true
    replant-when-ripe: false
cocoa:
    enabled: true
    replant-when-ripe: false
carrots:
    enabled: true
    replant-when-ripe: false
potatoes:
    enabled: true
    replant-when-ripe: false
beetroots:
    enabled: true
    replant-when-ripe: false
cactus:
    enabled: true
worlds:
    enable-per-world: false
    enabled-worlds:
    - ExampleWorld
check-for-updates: true
language: en
debug: false