Use Permissions: true
Wheat:
    Enabled: true
    Replant when ripe: false
    Plant on till: true
Sugar_cane:
    Enabled: true
Nether_wart:
    Enabled: true
    Replant when ripe: false
Cocoa_Beans:
    Enabled: true
    Replant when ripe: false
Carrot:
    Enabled: true
    Replant when ripe: false
Potato:
    Enabled: true
    Replant when ripe: false
Pumpkin:
    Enabled: true
    Replant when ripe: false
Melon:
    Enabled: true
    Replant when ripe: false
Beetroot:
    Enabled: true
    Replant when ripe: false
Worlds:
    Enable per world: false
    Enabled Worlds:
    - ExampleWorld
Check for updates: true
debug: false