##################################################################
#                          FarmAssist                            #
##################################################################
use-permissions: true

##################################################################
#                        Global Settings                         #
##################################################################
# Anything set under global settings will be globally set.
# Disables the "You are running the latest version message"
# Note that this outright disables the message,
# if you want to hide it, negate the farmassist.notify.update permission.
disable-latest-version: false

# Set renamed/seeds with nbt to true to have FarmAssist not
# take renamed/seeds with nbt seeds from your inventory when
# replanting.
ignore-seeds:
  renamed: false
  nbt: false

# Setting this to true will make it so players are no longer required to have seeds in their inventory to replant.
# Want to have this per player? Set this to false and give them the permission "farmassist.noseeds"
no-seeds: false
# Only relevant for when the above is set true. (I mean, you could still disable drops if you want)
# Disable the drops when replanting automatically.
# You can also use "farmassist.nodrops"
no-drops: false

# Even if you give the permission, these settings will override it.
# Example:
# player has farmassist.wheat
# wheat:
#   Enabled: false
# player won't be able to auto-replant wheat.
wheat:
  enabled: true
  replant-when-ripe: false
  plant-on-till: true

sugar_cane:
  enabled: true

nether_wart:
  enabled: true
  replant-when-ripe: false

cocoa:
  enabled: true
  replant-when-ripe: false

carrots:
  enabled: true
  replant-when-ripe: false

potatoes:
  enabled: true
  replant-when-ripe: false

beetroots:
  enabled: true
  replant-when-ripe: false

cactus:
  enabled: true

pitcher_plant:
  enabled: true
  replant-when-ripe: true

torch_flower:
  enabled: true
  replant-when-ripe: true

worlds:
  enable-per-world: false
  enabled-worlds:
    - ExampleWorld

check-for-updates: true

language: en

debug: false