ignore-nbt: ["itemsadder-*"]
disabled-crops: ["pumpkin", "melons", "sweet_berries", "cactus", "sugar_cane"]

enabled-worlds: ["world", "world_nether", "world_the_end"]

check-for-updates: true

locale:
  default: en
  # Allow player to have their own locales of the plugin.
  per-player-locale:
    enabled: true
    disabled-locales: []

lore:
  # Modify this to signify where the hoe lore is modified
  lore-start: 0

advanced-settings:
  max-cache-size: 100
  debug:
    enabled: false
    # Trace will show all debug messages, even for checks that may not be relevant
    level: debug

# Internal Config Version
config-version: 1.1