ignore-nbt: ["itemsadder-*"]
disabled-crops: ["pumpkin", "melons", "sweet_berries", "cactus", "sugar_cane"]

check-for-updates: true

locale:
  default: en
  # Allow player to have their own locales of the plugin.
  per-player-locale:
    enabled: true
    disabled-locales: []
advanced-settings:
  max-cache-size: 100
  debug: false

# Internal Config Version
config-version: 1.0