main: io.github.sarhatabaot.farmassistReboot
name: FarmAssistReboot
version: 0.1.0-SNAPSHOT
author: sarhatbaot
description: FarmAssist Rebooted
api-version: 1.13
commands:
  FarmAssist:
    description: Turn FarmAssist Featues on or off
    usage: /<command> toggle/global