main: io.github.sarhatabaot.farmassistreboot.FarmAssistReboot
name: FarmAssistReboot
version: ${project.version}
authors: [sarhatbaot]
website: https://www.spigotmc.org/resources/farmassistreboot.64064/
description: FarmAssistReboot Rebooted
api-version: 1.13
commands:
  FarmAssist:
    description: Turn FarmAssistReboot Featues on or off
    usage: /<command> toggle/global
permissions:
  farmassist.crops:
    default: false
    children:
      farmassist.wheat: true
      farmassist.sugar_cane: true
      farmassist.pumkin: true
      farmassist.melon: true
      farmassist.cocoa: true
      farmassist.nether_wart: true
      farmassist.carrots: true
      farmassist.potatoes: true
      farmassist.beetroots: true
      farmassist.cactus: true
  farmassist.wheat:
    default: false
  farmassist.sugar_cane:
    default: false
  farmassist.pumpkin:
    default: false
  farmassist.cocoa:
    default: false
  farmassist.nether_wart:
    default: false
  farmassist.carrots:
    default: false
  farmassist.potatoes:
    default: false
  farmassist.beetroots:
    default: false
  farmassist.cactus:
    default: false
  farmassist.melon:
    default: false
  farmassist.reload:
    default: op
  farmassist.toggle:
    default: op
  farmassist.global:
    default: op
  farmassist.update:
    default: op