main: io.github.sarhatabaot.farmassistreboot.FarmAssistReboot
name: FarmAssistReboot
version: 0.1.0-SNAPSHOT
author: sarhatbaot
description: FarmAssistReboot Rebooted
api-version: 1.13
commands:
  FarmAssist:
    description: Turn FarmAssistReboot Featues on or off
    usage: /<command> toggle/global